# Generated by Django 6.0.3 on 2026-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
