# Generated by Django 6.0.3 on 2026-03-12 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailychallenge',
            options={'ordering': ('level', 'question_number', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='dailychallenge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='compilation_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='failed_tests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='function_name',
            field=models.CharField(default='solve', max_length=100),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='hint1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='hint2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='hints_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='latest_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='penalty_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='points',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='runtime_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='timeout_errors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailychallengeset',
            name='easy_solved_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallengeset',
            name='hard_solved_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallengeset',
            name='medium_solved_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallengeset',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailychallengeset',
            name='solved_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('passed_tests', models.PositiveSmallIntegerField(default=0)),
                ('failed_tests', models.PositiveSmallIntegerField(default=0)),
                ('runtime_errors', models.PositiveSmallIntegerField(default=0)),
                ('compilation_errors', models.PositiveSmallIntegerField(default=0)),
                ('timeout_errors', models.PositiveSmallIntegerField(default=0)),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('penalty_points', models.PositiveSmallIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_history', to='daily_challenges.dailychallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('points_spent', models.PositiveIntegerField(default=0)),
                ('points_remaining', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-total_points', 'student__username'),
            },
        ),
    ]
