# Generated by Django 5.2.5 on 2026-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_challenges', '0004_dailychallengesession_studentpoints_daily_points'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailychallengequestion',
            new_name='daily_chall_templat_32b5f0_idx',
            old_name='daily_chall_template_9b66db_idx',
        ),
        migrations.RenameIndex(
            model_name='dailychallengequestion',
            new_name='daily_chall_date_us_9ad8de_idx',
            old_name='daily_chall_date_us_355771_idx',
        ),
    ]
