# Generated by hand for typed assignment support.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_teacherprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("file", "File Upload"),
                    ("quiz", "Quiz (MCQ)"),
                    ("code", "Coding"),
                ],
                default="file",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.TextField()),
                ("language", models.CharField(default="python", max_length=30)),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_submissions", to="teacher.assignment")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(choices=[("A", "Option A"), ("B", "Option B"), ("C", "Option C"), ("D", "Option D")], max_length=1)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_questions", to="teacher.assignment")),
            ],
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("selected_option", models.CharField(choices=[("A", "Option A"), ("B", "Option B"), ("C", "Option C"), ("D", "Option D")], max_length=1)),
                ("answered_at", models.DateTimeField(auto_now=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="teacher.quizquestion")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_answers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("question", "student")},
            },
        ),
    ]
