# Generated by hand for quiz evaluation results.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_assignment_type_quiz_codesubmission_quizanswer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(default=0)),
                ("feedback", models.TextField(blank=True)),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_results", to="teacher.assignment")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_results", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
