# Generated by Django 6.0.3 on 2026-03-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_performancerecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='performancerecord',
            new_name='teacher_per_classro_b16e85_idx',
            old_name='teacher_perf_classroo_4753ba_idx',
        ),
        migrations.RenameIndex(
            model_name='performancerecord',
            new_name='teacher_per_student_e12378_idx',
            old_name='teacher_perf_student_bcf32f_idx',
        ),
        migrations.RenameIndex(
            model_name='performancerecord',
            new_name='teacher_per_classro_d1ffa1_idx',
            old_name='teacher_perf_classroo_45d4a5_idx',
        ),
    ]
