# Generated by Django 6.0.3 on 2026-03-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminuserstate',
            new_name='adminpanel__teacher_09727a_idx',
            old_name='adminpanel_a_teacher_dcb6c9_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuserstate',
            new_name='adminpanel__suspend_0f9550_idx',
            old_name='adminpanel_a_suspend_d9ec1c_idx',
        ),
    ]
