# Generated by Django 6.0.3 on 2026-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_assessment', '0003_codingproblem_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='hint1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='hint2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
