# Generated by Django 5.2.5 on 2026-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='student_cha_session_d23ff9_idx',
            old_name='student_chat_session_42b7aa_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='student_cha_user_id_070d20_idx',
            old_name='student_chat_user_13f919_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='student_cha_user_id_c2b68f_idx',
            old_name='student_chat_user_512aa9_idx',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagequery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
