# Generated by Django 6.0.3 on 2026-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_adminpanel_a_teacher_dcb6c9_idx_adminpanel__teacher_09727a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Kodehax Academy', max_length=255)),
                ('support_email', models.EmailField(default='support@kodehax.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('enable_otp_login', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('challenge_time_limit_minutes', models.IntegerField(default=30)),
                ('auto_generate_challenges', models.BooleanField(default=True)),
                ('daily_challenge_base_points', models.IntegerField(default=10)),
                ('hint_cost_penalty', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
